@startuml
actor Client
participant PostOffice
participant Semaphore
participant PostOfficer

Client -> PostOffice ++ #005500 : AddNewClient(this)
activate Client

PostOffice -> Semaphore ++ #AA5500 : Wait()
Semaphore --> PostOffice -- #AA5500

PostOffice -> PostOfficer ++ #000055: ServeClient(c)
    PostOfficer -> PostOfficer ++ #0000AA : mutex.WaitOne()
    PostOfficer -> Client ++ #000088: Task(this)
    Client --> PostOfficer
    deactivate Client
    PostOfficer -> PostOfficer -- #0000AA : mutex.Release()
PostOfficer --> PostOffice
deactivate PostOfficer

PostOffice -> Semaphore ++ #AA5500 : Release()
Semaphore --> PostOffice -- #AA5500

PostOffice --> Client
deactivate PostOffice
deactivate Client
@enduml